name: Github Actions CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cv.tex
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '
    - name: Upload
      run: |
        # configure git
        git config --global user.name "Markus Kristiansen Nyland"
        git config --global user.email "markus.kristiansen.nyland@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch gh-pages git@github.com:MarkusKNyland/cv.git "$GITHUB_WORKSPACE/deploy"
        cp -f cv.pdf "$GITHUB_WORKSPACE/deploy/cv.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add cv.pdf
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
